# Generated by Django 5.0.6 on 2024-12-18 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0060_chathistory_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie_show', to='movie_app.serie'),
        ),
    ]
