# Generated by Django 5.0.6 on 2024-12-18 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0062_comment_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='serie',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie_comment', to='movie_app.serie'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_show', to='movie_app.serie'),
        ),
    ]
