# Generated by Django 5.0.6 on 2024-12-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0064_alter_comment_film_alter_comment_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_comments', to='movie_app.film'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_show', to='movie_app.film'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie_show', to='movie_app.serie'),
        ),
    ]
